variables:
  uploadDir: s3-virusscan-templates
  s3TargetDir: s3-virusscan-templates

trigger:
  tags:
    include:
      - '*'
  branches:
    exclude:
      - 'master'

stages:
  - stage: pushTemplate
    displayName: Push template to S3
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
    jobs:
      - job: pushTemplate
        displayName: Push template to S3
        workspace:
          clean: all
        steps:
          - bash: |
              REFERENCE=$(Build.SourceBranch)
              TAG_NAME=${REFERENCE#refs/tags/}  # Remove 'refs/tags/' prefix
              mkdir ${{ variables.uploadDir }}
              cp template.yaml ${{ variables.uploadDir }}/$TAG_NAME.yaml
          - task: S3Upload@1
            inputs:
              awsCredentials: 'live-aws'
              regionName: 'ap-southeast-2'
              bucketName: 'ep-development-tools'
              sourceFolder: '${{ variables.uploadDir }}'
              targetFolder: '${{ variables.s3TargetDir }}'
              filesAcl: 'public-read'
