variables:
  uploadDir: s3-virusscan-templates

stages:
  - stage: push
    displayName: Push template to S3
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
    jobs:
      - bash: |
          REFERENCE=$(Build.SourceBranch)
          TAG_NAME=${REFERENCE#refs/tags/}  # Remove 'refs/tags/' prefix
          mkdir ${{ variables.uploadDir }}
          cp template.yaml ${{ variables.uploadDir }}/$TAG_NAME.yaml
      - task: AmazonWebServices.aws-vsts-tools.S3Upload.S3Upload@1
        inputs:
          awsCredentials: live-aws
          regionName: ap-southeast-2
          bucketName: ep-development-tools
          sourceFolder: ${{ variables.uploadDir }}
          filesAcl: 'public-read'
